services:
  web:
    build: .
    container_name: asot-website
    ports:
      - "3000:3000"
    volumes:
      - ./gallery:/app/gallery
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
