services:
  web:
    build: .
    container_name: asot-website
    ports:
      - "3000:3000"
    volumes:
      - ./gallery:/app/gallery
      - ./milpacs:/app/milpacs
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://172.24.0.2:27017/ASOT
